Repository mosn/holmes, pull requests merged in 2022-01, with the labels that each got.

#33 fix spelling mistake
  readme.md
Labels: bug, First-time contributor, cla:yes, size/XS

#38 Add dangerous limit option and fix some typos.
  holmes.go
  options.go
  readme.md
Labels: bug, First-time contributor, cla:yes, size/M

#44 add golangci-lint to github action
  .github/workflows/ci.yml
Labels: size/S, cla:yes

#45 disable lll && skip example dir
  .github/workflows/ci.yml
  util.go
Labels: cla:yes, size/XS

#47 feat:cycle queue
  ring.go
Labels: First-time contributor, cla:yes, size/XS

#40 feat: add goroutines max number
  consts.go
  holmes.go
  options.go
  readme.md
  util.go
Labels: cla:yes, size/M

#50 fix:default specify error
  options.go
Labels: bug, cla:yes, size/XS

#51 perf:trimResult optimize
  consts.go
  util.go
Labels: size/S, cla:yes

#52 fix: example fix & init split log & trimResult opt
  example/channelblock/channelblock.go
  example/deadlock/deadlock.go
  example/slowlyleak/slowlyleak.go
  holmes.go
  util.go
Labels: bug, size/S, cla:yes
