Repository mosn/holmes, pull requests merged in 2022-02, with the labels that each got.

#53 feat: replace file handle atomic operation
  holmes.go
  log.go
  options.go
Labels: cla:yes, size/M

#54 feature: introduced a new heap profile way based on GC cycle.
  .github/workflows/ci.yml
  consts.go
  example/gcheap/.gitignore
  example/gcheap/README.md
  example/gcheap/gcheap.go
  example/gcheap/go.mod
  example/gcheap/go.sum
  example/gcheap/memory-spike.png
  example/gcheap/rand.sh
  holmes.go
  options.go
  util.go
Labels: First-time contributor, cla:yes, size/L

#56 style: change gcheap
  holmes.go
  options.go
  util.go
Labels: cla:yes, size/M

#57 expose SET api for some opts fields
  .github/workflows/ci.yml
  .gitignore
  go.mod
  holmes.go
  holmes_test.go
  options.go
  util.go
Labels: cla:yes, size/XL
