Repository mosn/holmes, pull requests merged in 2022-03, with the labels that each got.

#60 minor typo fixes in threadProfile.
  holmes.go
Labels: cla:yes, size/XS

#61 fix:repeat startup
  holmes.go
Labels: bug, cla:yes, size/XS

#64 fix issues/63
  holmes.go
Labels: bug, cla:yes, size/XS

#66 typo: defaultMemTrigger* => defaultThreadTrigger*.
  options.go
Labels: cla:yes, size/XS

#62 feature: added a new option UseGoProcAsCpuCore to get cpu core number by Go proc, also make the getUsage function simplier.
  .github/workflows/ci.yml
  Makefile
  holmes.go
  holmes_test.go
  options.go
  util.go
Labels: cla:yes, size/L

#65 feature: support shrink thread when the thread num exceed the threshold.
  .github/workflows/ci.yml
  holmes.go
  holmes_test.go
  options.go
Labels: question, cla:yes, size/L

#67 bugfix: we should init the finCh when New holmes instance.
  holmes.go
Labels: question, size/S, cla:yes

#70 fix linter
  .github/workflows/ci.yml
  Makefile
Labels: bug, cla:yes, size/XS

#68 change: write the thread and goroutine profiles into two files in threadProfile
  holmes.go
  util.go
Labels: cla:yes, size/M

#73 fix:mem Index
  util.go
Labels: bug, cla:yes, size/XS

#71 feature: added a reporter plugin to upload profile to a central platform.
  Makefile
  go.mod
  go.sum
  holmes.go
  reporters/http_reporter/http_reporter.go
  reporters/http_reporter/http_reporter_test.go
Labels: cla:yes, size/L

#72 fix:notes typo and config panic may occur
  holmes.go
  options.go
Labels: bug, size/S, cla:yes

#76 change module from github.com/mosn/holmes to mosn.io/holmes.
  example/1gbslice/1gbslice.go
  example/alloc/alloc.go
  example/channelblock/channelblock.go
  example/cpu_explode/cpu_explode.go
  example/deadlock/deadlock.go
  example/deadloop/deadloop.go
  example/gcheap/gcheap.go
  example/gcheap/go.mod
  example/run_in_docker/run_in_docker.go
  example/slowlyleak/slowlyleak.go
  example/thread_trigger/thread_trigger.go
  go.mod
Labels: size/S, cla:yes

#78 profile type name unify
  consts.go
Labels: First-time contributor, cla:yes, size/XS

#80 changed to use mosn ErrorLogger as the logger interface.
  .github/workflows/ci.yml
  .gitignore
  Makefile
  consts.go
  example/1gbslice/1gbslice.go
  example/alloc/alloc.go
  example/channelblock/channelblock.go
  example/cpu_explode/cpu_explode.go
  example/deadlock/deadlock.go
  example/deadloop/deadloop.go
  example/gcheap/gcheap.go
  example/gcheap/go.mod
  example/gcheap/go.sum
  example/run_in_docker/run_in_docker.go
  example/slowlyleak/slowlyleak.go
  example/thread_trigger/thread_trigger.go
  go.mod
  go.sum
  holmes.go
  log.go
  options.go
  tool/build-example.sh
  util.go
Labels: cla:yes, size/XXL

#81 change: also write to a file when enabled text dump, just like binary dump.
  consts.go
  holmes.go
  util.go
Labels: question, cla:yes, size/M

#82 change: support different cool down time for each check type.
  consts.go
  example/1gbslice/1gbslice.go
  example/alloc/alloc.go
  example/channelblock/channelblock.go
  example/cpu_explode/cpu_explode.go
  example/deadlock/deadlock.go
  example/deadloop/deadloop.go
  example/gcheap/gcheap.go
  example/run_in_docker/run_in_docker.go
  example/slowlyleak/slowlyleak.go
  example/thread_trigger/thread_trigger.go
  holmes.go
  holmes_test.go
  options.go
  readme.md
  reporters/reporter_test.go
Labels: cla:yes, size/L

#83 change: expose the EnableShrinkThread/DisableShrinkThread methods instead the Enable argument in WithShrinkThread method.
  holmes.go
  holmes_test.go
  options.go
Labels: size/S, cla:yes

#77 fix: profileReporter internal event circulation
  go.sum
  holmes.go
  reporters/http_reporter/http_reporter.go
  reporters/http_reporter/http_reporter_test.go
  reporters/reporter_test.go
Labels: bug, cla:yes, size/L

#85 fix some issues in #77. eg. add recover to catch panic.
  go.sum
  holmes.go
Labels: bug, cla:yes, size/M

#86 Update readme.md and add Chinese version
  doc/example.md
  doc/zh.md
  readme.md
Labels: cla:yes, size/XL

#91 feat:supports dump goroutine to logger and fix typos
  doc/zh.md
  holmes.go
  options.go
  readme.md
  reporters/reporter_test.go
Labels: bug, cla:yes, size/M

#93 docs: add withDumpTo logs
  doc/zh.md
  readme.md
Labels: cla:yes, size/XS

#94 stop remind typos
  holmes.go
Labels: cla:yes, size/XS

#92 fix: #89
  holmes.go
  util.go
Labels: bug, size/S, cla:yes
